spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
# for maria
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#for mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.session.jdbc.initialize-schema=always